spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.172.165:3306/kaletgo_sys
    username: fireway
    password: chw390099591
    driverClassName: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false


mybatis:
  mapperLocations: classpath*:/mapping/*Mapper.xml
  typeAliasesPackage: com.fireway.kaletgo.model

#classpath:config/logback-spring.xml

#Dubbo
#ZooKeeper
dubbo:
  registry:
    address: 120.78.172.165:2181