server:
  port: 8088
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
  resources:
    static-locations: classpath:/static/
  freemarker:
      template-loader-path: classpath:/templates/
      suffix: .html
      request-context-attribute: request
      charset: UTF-8
      cache: false
#日志
logging:
  config: classpath:config/logback-spring.xml

#Dubbo
#ZooKeeper
dubbo:
    registry:
        address: 120.78.172.165:2181